// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4nhbsXWdtMsKJRjp2o-9taq7HXo4hzws',
    appId: '1:752991501369:web:04a7b48f9774f88303a1e8',
    messagingSenderId: '752991501369',
    projectId: 'enterprises-attendance',
    authDomain: 'enterprises-attendance.firebaseapp.com',
    storageBucket: 'enterprises-attendance.firebasestorage.app',
    measurementId: 'G-1WE6DRXYZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGifGUQ5yStDxmgVQ7WccGLWITw6SVrHU',
    appId: '1:752991501369:android:57d71239e912abec03a1e8',
    messagingSenderId: '752991501369',
    projectId: 'enterprises-attendance',
    storageBucket: 'enterprises-attendance.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rBuR7fAbrERy7ixnSMe7e2p8t284iwI',
    appId: '1:752991501369:ios:efa8f07f9965efdb03a1e8',
    messagingSenderId: '752991501369',
    projectId: 'enterprises-attendance',
    storageBucket: 'enterprises-attendance.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rBuR7fAbrERy7ixnSMe7e2p8t284iwI',
    appId: '1:752991501369:ios:efa8f07f9965efdb03a1e8',
    messagingSenderId: '752991501369',
    projectId: 'enterprises-attendance',
    storageBucket: 'enterprises-attendance.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4nhbsXWdtMsKJRjp2o-9taq7HXo4hzws',
    appId: '1:752991501369:web:7af10e7aefa936e403a1e8',
    messagingSenderId: '752991501369',
    projectId: 'enterprises-attendance',
    authDomain: 'enterprises-attendance.firebaseapp.com',
    storageBucket: 'enterprises-attendance.firebasestorage.app',
    measurementId: 'G-JY96HGT3M3',
  );
}
